version: "3"

services:
  mongodb:
    image: mongo:latest
    command: --bind_ip_all
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - type: volume
        source: db-data
        target: /data/db
 
volumes:
  db-data:
